## UCI SECOM(RandomForest)-2
#### Data preprocessing method: 결측값50%넘는 열 삭제후 남은 결측값은 fillna함수의 method='ffill'&'bfill'을 이용해 채운다. 이후 고유치 개수가 1인 열을 제거한다.

In [1]:
#Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
%matplotlib inline

In [2]:
# Read the data
data = pd.read_csv('uci-secom.csv')

In [3]:
# Data shape 및 상위 5개 열 보기
print(data.shape)
data.head()

(1567, 592)

,Time,0,1,2,3,4,5,6,7,8,...,581,582,583,584,585,586,587,588,589,Pass/Fail
0,2008-07-19 11:55:00,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,...,NaN,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN,-1
1,2008-07-19 12:32:00,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,...,208.2045,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045,-1
2,2008-07-19 13:17:00,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,...,82.8602,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602,1
3,2008-07-19 14:43:00,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,...,73.8432,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432,-1
4,2008-07-19 15:22:00,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,...,NaN,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432,-1

In [4]:
# include='all'하면 입력의 모든 열이 데이터 출력으로 포함, 기본값인 'None'은 수치데이터가 있는 열만 결과에 포함
data.describe(include='all')

,Time,0,1,2,3,4,5,6,7,8,...,581,582,583,584,585,586,587,588,589,Pass/Fail
count,1567,1561.000000,1560.000000,1553.000000,1553.000000,1553.000000,1553.0,1553.000000,1558.000000,1565.000000,...,618.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1567.000000
unique,1534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2008-10-15 01:52:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,3014.452896,2495.850231,2200.547318,1396.376627,4.197013,100.0,101.112908,0.121822,1.462862,...,97.934373,0.500096,0.015318,0.003847,3.067826,0.021458,0.016475,0.005283,99.670066,-0.867262
std,NaN,73.621787,80.407705,29.513152,441.691640,56.355540,0.0,6.237214,0.008961,0.073897,...,87.520966,0.003404,0.017180,0.003720,3.578033,0.012358,0.008808,0.002867,93.891919,0.498010
min,NaN,2743.240000,2158.750000,2060.660000,0.000000,0.681500,100.0,82.131100,0.000000,1.191000,...,0.000000,0.477800,0.006000,0.001700,1.197500,-0.016900,0.003200,0.001000,0.000000,-1.000000
25%,NaN,2966.260000,2452.247500,2181.044400,1081.875800,1.017700,100.0,97.920000,0.121100,1.411200,...,46.184900,0.497900,0.011600,0.003100,2.306500,0.013425,0.010600,0.003300,44.368600,-1.000000
50%,NaN,3011.490000,2499.405000,2201.066700,1285.214400,1.316800,100.0,101.512200,0.122400,1.461600,...,72.288900,0.500200,0.013800,0.003600,2.757650,0.020500,0.014800,0.004600,71.900500,-1.000000
75%,NaN,3056.650000,2538.822500,2218.055500,1591.223500,1.525700,100.0,104.586700,0.123800,1.516900,...,116.539150,0.502375,0.016500,0.004100,3.295175,0.027600,0.020300,0.006400,114.749700,-1.000000
max,NaN,3356.350000,2846.440000,2315.266700,3715.041700,1114.536600,100.0,129.252200,0.128600,1.656400,...,737.304800,0.509800,0.476600,0.104500,99.303200,0.102800,0.079900,0.028600,737.304800,1.000000

## 1. Data Preprocessing

In [5]:
# Check data's Null values
data.isnull().any().any()

True

위의 결과를 통해 데이터에 결측값이 있다는 것을 확인했고, 결측값이 50% 이상인 열은 삭제하고, 나머지는 fillna의 method='ffill'을 통해 결측값을 앞 방향으로 채운 뒤

In [6]:
# Column에서 결측값의 percentage를 나타내는 함수 정의
# pd.concat->데이터 프레임 결합
# df.shape[0]은 데이터 전체 열의 개수
def null_values(df):
    nv=pd.concat([df.isnull().sum(), 100 * df.isnull().sum()/df.shape[0]],axis=1).rename(columns={0:'Missing_Records', 1:'Percentage (%)'})
    return nv[nv.Missing_Records>0].sort_values('Missing_Records', ascending=False)

In [7]:
# Get rid of 'Time' column because it's meaningless
data=data.drop(['Time'],axis=1)

In [8]:
df_na = null_values(data)
df_na

     Missing_Records  Percentage (%)
292             1429       91.193363
293             1429       91.193363
157             1429       91.193363
158             1429       91.193363
358             1341       85.577537
..               ...             ...
456                1        0.063816
218                1        0.063816
356                1        0.063816
457                1        0.063816
589                1        0.063816

[538 rows x 2 columns]

In [9]:
# 결측값의 비율이 50% 넘는 열 개수 확인
df_na = df_na[df_na["Percentage (%)"] > 50]
df_na
df_na.shape

(28, 2)

In [10]:
# 결측값의 비율이 50% 넘는 열 확인
df_na.index

Index(['292', '293', '157', '158', '358', '85', '492', '220', '518', '246',
       '245', '516', '517', '110', '384', '382', '383', '109', '244', '111',
       '580', '578', '581', '579', '73', '72', '345', '346'],
      dtype='object')

In [11]:
# 결측값의 비율이 50% 넘는 열 삭제
data = data.drop(axis=1, columns=df_na.index)
data.shape

(1567, 563)

본래 592개의 열에서 50%가 넘는 28개의 열이 삭제됐음을 확인할 수 있음

In [12]:
# 나머지 열의 결측값은  나머지는 fillna의 method='ffill'과 'bfill'을 통해 결측값을 앞뒤 방향으로 채운다.
data.fillna(method='ffill', inplace=True)
data.fillna(method='bfill', inplace=True)
data

,0,1,2,3,4,5,6,7,8,9,...,577,582,583,584,585,586,587,588,589,Pass/Fail
0,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,0.0162,...,14.9509,0.5005,0.0118,0.0035,2.3630,0.0096,0.0201,0.0060,208.2045,-1
1,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,-0.0005,...,10.9003,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045,-1
2,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,0.0041,...,9.2721,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602,1
3,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,-0.0124,...,8.5831,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432,-1
4,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,-0.0031,...,10.9698,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1562,2899.41,2464.36,2179.7333,3085.3781,1.4843,100.0,82.2467,0.1248,1.3424,-0.0045,...,11.7256,0.4988,0.0143,0.0039,2.8669,0.0068,0.0138,0.0047,203.1720,-1
1563,3052.31,2522.55,2198.5667,1124.6595,0.8763,100.0,98.4689,0.1205,1.4333,-0.0061,...,17.8379,0.4975,0.0131,0.0036,2.6238,0.0068,0.0138,0.0047,203.1720,-1
1564,2978.81,2379.78,2206.3000,1110.4967,0.8236,100.0,99.4122,0.1208,1.4333,-0.0061,...,17.7267,0.4987,0.0153,0.0041,3.0590,0.0197,0.0086,0.0025,43.5231,-1
1565,2894.92,2532.01,2177.0333,1183.7287,1.5726,100.0,98.7978,0.1213,1.4622,-0.0072,...,19.2104,0.5004,0.0178,0.0038,3.5662,0.0262,0.0245,0.0075,93.4941,-1
1566,2944.92,2450.76,2195.4444,2914.1792,1.5978,100.0,85.1011,0.1235,1.4622,-0.0072,...,22.9183,0.4987,0.0181,0.0040,3.6275,0.0117,0.0162,0.0045,137.7844,-1

In [13]:
data.isnull().any().any()

False

결측값이 더이상 없음을 확인할 수 있다.

#### 추가로 고유값이 1개뿐인 열을 삭제하는 전처리 진행

In [14]:
# nunique() 함수를 써서 5열의 고유치 개수를 확인
data["5"].nunique()

1

In [15]:
# Column '5'와 같이 고유값이 1개인 열을 저장하는 unique_columns함수 생성
def unique_columns(df):
    uni_col_list = []
    for column in df.columns:
        if df[column].nunique() == 1:
            uni_col_list.append(column)
    return uni_col_list

In [16]:
# 고유치 개수가 1개인 열의 개수 확인
len(unique_columns(data))

116

In [17]:
data.shape

(1567, 563)

In [18]:
data = data.drop(axis=1, columns=unique_columns(data))
data.shape

(1567, 447)

고유치 개수가 1개인 열 116개가 지워진 것을 확인할 수 있다.

### Data Scaling
- 1. StandardScaler 
- 2. PCA 차원축소

In [19]:
# Train/Test Dataset split을 위해 Dataset을 Data/Target값으로 분리
X = data.iloc[:, 1:-1]
y = data.iloc[:, -1]

In [20]:
from imblearn.over_sampling import SMOTE
X_resample, y_resample  = SMOTE(random_state=1).fit_sample(X, y.values.ravel())

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_resample, y_resample,random_state=50)

(1) StandardScaler: 각 feature의 평균을 0, 분산을 1로 변경, 모든 feature들이 같은 Scale을 갖게된다.

In [22]:
y_train

array([ 1, -1,  1, ...,  1, -1,  1], dtype=int64)

#### ※ Scaler를 사용하기 전에 주의할 점
scaler는 fit과 transform 매서드를 지니고 있다. fit 매서드로 데이터 변환을 학습하고, transform 매서드로 실제 데이터의 스케일을 조정한다.
이때! fit 매서드는 학습용 데이터에만 적용해야한다. 그 후 transform 매서드를 학습용 데이터와 테스트 데이터에 적용한다.

In [23]:
from sklearn.preprocessing import StandardScaler 
sc= StandardScaler()
X_sc = sc.fit_transform(X)
X_train_sc = sc.fit_transform(X_train)
print('Features Min value before Scale : \n {}'. format(X_train.min(axis=0)))
print('Features Max value before Scale : \n {}'. format(X_train.max(axis=0)))
print('Features Min value after Scale : \n {}'. format(X_train_sc.min(axis=0)))
print('Features Max value after Scale : \n {}'. format(X_train_sc.max(axis=0)))
X_test_sc = sc.transform(X_test)

Features Min value before Scale :
 1      2158.7500
2      2060.6600
3         0.0000
4         0.6815
6        82.1311
         ...
585       1.2845
586      -0.0060
587       0.0032
588       0.0010
589       0.0000
Length: 445, dtype: float64
Features Max value before Scale :
 1      2846.4400
2      2315.2667
3      3715.0417
4      1112.4728
6       129.2522
         ...
585      99.3032
586       0.1028
587       0.0799
588       0.0286
589     737.3048
Length: 445, dtype: float64
Features Min value after Scale :
 [-4.59693849e+00 -5.21855591e+00 -3.65246862e+00 -4.94534582e-02
 -3.46284616e+00 -2.00459449e+01 -4.38926545e+00 -3.87392042e+00
 -4.05116157e+00 -2.76505582e+01 -6.22659101e+00 -2.49312193e+00
 -2.01571114e+00 -9.08158150e-01 -3.73839158e+01 -8.42110939e+00
 -1.56323595e+01 -1.50629790e+01 -2.09743849e+00 -7.36140792e+00
 -4.56617017e+00 -5.62079276e+00 -5.64337705e+00 -7.25056305e+00
 -4.62756057e+00 -2.97373008e+00 -4.32739559e+00 -4.75654471e+00
 -3.22367609e+00 -1.10405813e+00 -9.86975173e-01 -7.03839678e-01
 -3.73066434e-01 -8.81380109e+00 -5.03773769e+00 -4.24255012e+00
 -4.61209888e+00 -2.66774877e+00 -1.65714615e+00 -2.28837714e+00
 -3.54100179e+00 -3.58667736e+00 -3.08694741e+00 -4.07659827e+00
 -3.33666541e+00 -3.25048038e+00 -2.04649003e+00 -1.90485176e+01
 -1.76647330e+01 -2.12638581e+00 -9.21441256e+00 -4.39407449e+00
 -5.02966311e+00 -3.65519524e+00 -5.62493579e+00 -3.67437424e+00
 -3.69843961e+00 -1.97222936e+00 -2.67025454e+00 -3.26581990e+00
 -6.80635008e+00 -5.63786150e-02 -9.64503829e+00 -3.91762666e+00
 -2.66563602e+00 -2.13540711e-02 -4.10744468e+00 -3.83346350e+00
 -3.33056016e+00 -7.31576190e+00 -2.86927028e+00 -2.38580173e+00
 -4.85898525e+00 -3.57495878e+00 -3.27196514e+00 -3.48185775e+00
 -4.86282489e+00 -1.40794475e+01 -3.68397066e+00 -1.10799630e+00
 -4.07458078e+00 -4.74310943e+00 -4.24366109e+00 -6.25203476e+00
 -9.25157804e+00 -4.83207267e+00 -8.12591838e+00 -1.03342063e+01
 -7.18862836e+00 -8.89006511e+00 -8.91231866e+00 -7.79751156e+00
 -7.94531888e+00 -1.16873553e+01 -9.77739367e+00 -5.08113918e+00
 -6.26538545e+00 -3.83017697e+00 -6.63864685e+00 -8.51631050e+00
 -1.45222268e-01 -4.52433373e+00 -1.11561219e+01 -1.02474585e+00
 -9.89807005e+00 -1.62599491e+01 -5.01632915e+00 -3.91257668e+00
 -2.76930030e+00 -6.92564919e+00 -3.63168642e+00 -3.49290923e+00
 -1.80511266e+00 -2.80127158e+00 -1.44983410e+01 -3.30580335e+00
 -4.77076104e+00 -2.19117689e+00 -2.48002535e+00 -3.66834754e+00
 -2.21088423e+00 -1.10981343e+00 -2.08057595e+00 -2.27680048e+00
 -3.39121914e+00 -1.66640681e+00 -3.11879832e-02 -1.57128686e+00
 -3.72695133e+00 -1.48550413e+00 -1.81949333e+00 -1.67271582e+00
 -6.03796624e-01 -4.27929727e-01 -1.82116790e+00 -5.09820339e-01
 -4.81649307e-02 -1.22954271e+00 -1.31892477e+00 -3.87401156e-01
 -6.98917094e-01 -8.45647502e-01 -9.89171272e-01 -1.03089781e+00
 -7.52826533e-01 -1.01420661e+00 -4.84992856e-01 -5.50638787e-01
 -1.30774693e+00 -1.47376803e+00 -2.00929302e+00 -1.87293613e+00
 -2.62564133e+00 -2.12867194e+00 -3.16584622e+00 -3.75157832e+00
 -3.16572080e+00 -3.15479432e+00 -2.49190231e+00 -1.28741810e+00
 -3.10307505e+00 -2.18603795e+00 -2.03119304e+00 -3.64305616e+00
 -1.19609635e+00 -8.83515891e-01 -1.54153586e+00 -1.89639068e+00
 -5.05596993e-01 -5.18843008e-01 -1.26173935e+00 -1.11855132e+00
 -6.18067810e-01 -2.25348857e+00 -1.73115351e+00 -8.56176335e-01
 -1.53245453e+00 -5.67376138e-02 -7.79833734e-01 -2.13540711e-02
 -1.22771734e+00 -2.62026932e+00 -2.13540711e-02 -1.32984454e+00
 -1.83031049e+00 -1.45817027e+00 -1.12943109e+00 -1.35594900e+00
 -2.67988321e+00 -3.07105897e+00 -1.54267716e+00 -2.51702926e+00
 -1.74744828e+00 -1.75647107e+00 -1.86085509e-01 -2.70867969e+00
 -6.76703461e-01 -2.14963105e+00 -1.38064917e+00 -1.27364606e+00
 -2.24707311e+00 -2.29915946e+00 -9.45063603e-01 -5.58349178e-01
 -1.40915884e-01 -1.83827899e+00 -1.17491622e-01 -6.27292696e-02
 -1.14914345e+00 -1.43901192e+00 -2.58394160e+00 -1.78859987e+00
 -1.96576682e+00 -2.30532375e+00 -1.72311157e+00 -2.21038603e+00
 -2.22706685e+00 -3.32778919e+00 -1.68275860e+00 -3.11897414e-02
 -1.64111457e+00 -3.80894073e+00 -1.56064541e+00 -1.90043423e+00
 -1.64696737e+00 -6.11585526e-01 -4.42081133e-01 -1.86339782e+00
 -4.57523391e-01 -4.56653189e-02 -1.26782874e+00 -1.44706813e+00
 -4.14872658e-01 -7.36870717e-01 -7.82147814e-01 -9.01689429e-01
 -1.02535164e+00 -7.44568897e-01 -8.80673286e-01 -4.37651125e-01
 -4.94161767e-01 -1.54926172e+00 -1.47593002e+00 -2.14317004e+00
 -1.91942450e+00 -2.80252626e+00 -2.08051942e+00 -3.14088041e+00
 -4.21191381e+00 -3.14049514e+00 -3.34684544e+00 -2.40208485e+00
 -1.22554681e+00 -3.30854626e+00 -2.13734349e+00 -2.02056424e+00
 -3.24978889e+00 -1.25140630e+00 -9.15043807e-01 -1.71925917e+00
 -1.87998865e+00 -9.36796645e-01 -4.45349322e-01 -1.27297383e+00
 -1.05473271e+00 -5.52741924e-01 -7.80994219e-01 -1.52884070e+00
 -6.60274141e-01 -1.41585380e+00 -5.83272031e-02 -7.30534599e-01
 -2.13540711e-02 -1.22843708e+00 -2.58406721e+00 -2.13540711e-02
 -1.08145836e+00 -1.88575033e+00 -1.44310293e+00 -1.08683514e+00
 -1.61675110e+00 -2.62954753e+00 -3.08277963e+00 -1.54435727e+00
 -2.52704021e+00 -1.58125595e+00 -1.59843663e+00 -1.72781582e-01
 -2.71277008e+00 -6.83875272e-01 -2.11957692e+00 -1.39651392e+00
 -1.36747825e+00 -1.43372091e+00 -1.77649603e+00 -2.37731165e+00
 -2.66412880e+00 -9.70486947e-01 -6.00442937e-01 -1.41193475e-01
 -1.89648517e+00 -1.15042945e-01 -5.67268436e-02 -1.23994627e+00
 -1.42411360e+00 -2.93727189e+00 -1.74887218e+00 -1.75781228e+00
 -2.43036061e+00 -1.07036598e+00 -2.07681300e+00 -2.26408554e+00
 -3.35353681e+00 -1.80894179e+00 -6.48021009e-01 -1.46046824e+00
 -3.75428154e+00 -1.55111759e+00 -1.14949298e+00 -1.06523353e+00
 -5.61948120e-01 -5.68310315e-01 -1.89391888e+00 -5.62817089e-01
 -2.96480446e-01 -1.20214058e+00 -1.20003757e+00 -3.35305742e-01
 -6.22124576e-01 -4.42488759e-01 -5.30500543e-01 -8.68487509e-01
 -1.00091318e+00 -3.91581325e-01 -2.82332360e-01 -2.45056027e-01
 -1.30058376e+00 -1.13086318e+00 -1.76851826e+00 -1.78932234e+00
 -2.59800034e+00 -2.15218490e+00 -3.41256615e+00 -4.05929159e+00
 -2.83276447e+00 -3.14567937e+00 -2.48305340e+00 -1.29459845e+00
 -3.10796771e+00 -2.18567314e+00 -1.99075440e+00 -3.59191105e+00
 -1.28262710e+00 -9.88446308e-01 -1.57342022e+00 -1.73155997e+00
 -5.04937755e-01 -9.71197930e-01 -1.22656655e+00 -1.14307402e+00
 -7.90600660e-01 -2.81723809e+00 -1.87178787e+00 -1.69934841e+00
 -1.45029762e+00 -1.69925347e+00 -6.08312469e-01 -2.13540711e-02
 -1.32251194e+00 -1.93123681e+00 -1.21477740e+00 -1.18558161e+00
 -1.03861543e+00 -9.51555729e-01 -1.21572500e+00 -9.57986506e-01
 -1.40482500e+00 -1.34752470e+00 -2.23062897e+00 -1.72517977e+00
 -1.76151150e+00 -1.72008818e-01 -2.68517301e+00 -1.17389657e+00
 -2.13836471e+00 -8.15027623e-01 -8.28466517e-01 -1.52789936e+00
 -1.00476196e+00 -8.73784242e-01 -5.22424828e-01 -1.62362596e-01
 -1.91755821e+00 -1.13039535e-01 -2.42714270e-01 -1.12291202e+00
 -1.42520500e+00 -2.51689828e+00 -1.82156950e+00 -1.95516388e+00
 -2.36214194e+00 -2.30701390e+00 -2.47716764e+00 -3.56780526e+00
 -2.76238129e+00 -1.63482730e+00 -4.77373792e+00 -1.50113248e+00
 -1.03698745e+00 -2.22133740e+00 -8.36437102e-01 -1.05505017e+00
 -2.33563722e+00 -7.91110444e-01 -1.74919357e+00 -2.19704880e+00
 -7.91887765e-01 -1.24400229e+00 -1.35552663e+00 -1.20582997e+00
 -1.37663584e+00 -2.77925332e+00 -3.12273736e+00 -2.28159173e+00
 -1.53260897e+00 -2.34454472e+00 -1.55901324e+00 -2.29958259e+00
 -1.78853492e+00 -1.18934351e+01 -3.78463223e+00 -2.53793219e-01
 -1.35088368e+00 -2.65145201e-01 -1.43700032e+00 -2.56063391e-01
 -1.13866384e+00 -6.32897561e+00 -7.88925731e-01 -8.96223798e-01
 -7.69836671e-01 -2.42889596e+00 -1.68339911e+00 -1.68311113e+00
 -1.19674355e+00]
Features Max value after Scale :
 [ 4.83898447  4.28789466  6.13079225 33.1087151   5.13252185  1.0690823
  2.99237087  5.73980077  6.04293548  1.89789607 25.19269455  3.91241938
 34.66368996 45.63444846  1.30049083  4.17128878  2.99108722  3.19650199
  7.08759208  2.75323821  4.58982554  5.61400321  0.90725149  0.52456854
  0.76234157  2.81376656  3.05374635  3.31194955  2.39149692  9.69877182
  9.27906731  8.81380225 13.51805179  0.70382891  3.65369551  3.02128649
  9.8208043   0.89611479 16.91117064  3.82838334  6.66594296  5.30471148
  5.11143783  1.90937068  5.60763352  4.6816227   1.7575641   3.66971155
  3.09424382  3.09803275  1.40505166  2.78704122  3.23802249 17.35925463
  3.53002162  3.5095029  21.23205291 26.14571599  4.92797934 12.41791245
  6.01515306 32.78240846  5.38150347 11.65420531  4.11696301 46.8294779
  9.84081818  3.50775796  4.80216316  5.88971406  4.24601854  2.8860894
  3.47672676  4.14436607  3.23174703  3.89150503  4.34232837  0.81331551
  5.89881104 17.65562837  5.72289157  4.69018772  9.67255923  5.02952008
  7.64012893  8.44254855 10.22321424  7.57195164 11.81018906  6.42155437
  9.66001706  4.97011837  9.75455077  7.09063898  4.3349057   6.34202706
  4.61229842  5.08924404  0.47262789  2.8551075  18.06651059  4.09368452
  0.64161713 46.07454867  3.32185919  1.47662492  9.6893923   2.87418532
  3.98312699  2.62304901  2.70511057  5.42425867  5.15103052  4.72294943
  3.13574407  2.73218998  1.95700107 10.95568844  3.02724472  2.86063959
  9.33484113 17.40688145  3.04734284  4.42514985  5.51704452  5.37776518
 33.10736528 32.22946872  7.35114044  9.04557247  8.92059224 10.75070999
 42.66322432 46.21977719  4.72360841 24.00499328 46.80988969 24.9939205
 39.64952477 15.29890411 31.07292615  5.91175286  5.65110443  6.34434908
  5.26002404  4.98468314  4.97594435  5.35918601 11.98935976 11.67137927
  9.23310199  3.4989117   3.0244052   7.08311712  3.69212101  3.42293361
  3.69183355  3.73045498  2.83845114  5.56479506 10.18871023 15.33337383
 12.50126206  7.48747227 31.71715835 42.99478032 39.17132079  7.14989719
  9.54595218 27.95947736 27.9226254  18.36164087 26.16350851 25.14961172
 25.70698238 40.83475015 32.01979486 25.61990624 34.74199307 46.8294779
 32.67599533  3.92736498 46.8294779   8.79732533  9.21591688 19.26491362
 22.64579449 15.42837538  9.36771959  8.11697154 14.93396863  4.53643429
  8.7471216   7.23124335 15.8452473   4.81649954 19.08445733  6.11033697
  9.32764974 13.28484704 12.15347128  8.82994781  7.91711375 22.89728563
 19.40851996 20.42442531 33.7885473  46.81945625 19.55305272  7.89779916
  4.94745093  3.20723632  3.09582849  5.80073388 17.0865557   2.94892579
  4.96076041  6.68044713  6.41077367 33.10645483 30.44321011  8.03478034
  7.97071235 11.03008362  9.71799529 42.45091747 46.28822611  5.45367107
 29.58081354 46.8114962  23.68822924 40.02043152 24.33492335 30.18589808
  6.03592727  5.41970181  7.23016425  5.3469266   5.30110797  5.34073793
  5.54803014 10.95152833 11.29700673  8.55822317  3.09825557  3.87887883
  8.14010386  3.46005081  3.54518833  3.45968768  3.59431677  3.00775796
  5.43762317  7.95288438 12.82892244 12.14277157  6.0881139  32.27772074
 43.0931978  38.66144525  6.12273796 14.40335306 36.82742825 31.1184673
 18.8831086  35.32188162 34.75260113 23.55597441 43.1525658  37.23571432
 27.12555004 34.87187135 46.8294779  37.22644811  4.51935287 46.8294779
 12.4394476   8.83921535 20.99433012 23.37687217 11.40526837  7.91015138
  6.08831876 12.43715363  4.11257571  9.20401708  8.95951805 16.72286703
  4.29636488 17.94953014  5.49169065 11.4992194   9.94870787 12.18777931
 13.33266411 12.60665099  8.50374554 17.33916148 23.05231376 19.42832028
 19.83198824 33.83994069 46.82056207 19.20567125  6.90032287  4.90474635
  2.75251126  2.89359821  6.09490616 17.24212246  2.89751102  4.54139139
  5.54847981  5.62657267 27.14724317 33.33850573  7.18009133  8.43152568
  2.60995607  2.33417243 43.10879808 45.70569185  7.21408545 22.00370202
 44.91983053 24.60921412 40.89212224 14.97937221 32.76386983  6.84684596
  6.78187882  7.76956767  3.51661791  7.05006484  7.05878732  7.04933579
 12.20802218 20.6606787  16.24769593  3.40526176  2.5966184   6.64650072
  3.61172705  3.36106799  3.77346179  3.68333663  2.83492679  5.19963277
 10.65106095 14.61692353 13.2376372   7.68459118 30.22652648 41.47838051
 38.78117606  8.95476312  9.85239118  3.8088831  29.6410443  18.98185308
 21.47378415  7.94698959 15.24680857 17.23314559 34.03657622  9.91655246
 35.32867505 46.8294779  29.893756    4.48159753  2.60656036  4.75124407
  4.21236749  4.14459339  2.66231528  3.13472704  2.80259414  3.47233901
  5.26468828  9.23349578  7.06288084 16.4133202   4.99892364  9.58572237
  5.93283403  2.50189673  2.40366115  9.13774638  2.13855606 13.18048861
 22.96921462  8.68053595 19.00367501 34.25596242 46.53057462 20.12621931
  7.86132254  4.86387288  3.0996252   3.12022524  5.85549267  3.03027707
 12.01930782  8.47098513 12.17022953  8.36589886  4.08207935  2.30948453
 10.80209609 13.8138408  15.26006187 10.01951697 13.30924232 15.42977102
  7.75351611 14.01887793 15.44360888  6.02143657  3.83985698  8.06475196
  3.65378741  6.91830846  5.72509105  5.50450597  6.30328968  5.68622644
  6.86931708  5.15268383  6.23634791  3.29103967  2.19149556  6.39282272
  9.87369218  7.89471391  8.59257542  6.23769333  8.48908254  2.92032564
 41.31980777 42.31703838 41.72947877  7.18626061  7.59688641  8.74053493
  7.61542838]

(2) PCA차원축소

- 많은 feature로 구성된 다차원 데이터 세트의 차원을 축소해 새로운 차원의 데이터 세트를 생성하는 것
-  일반적으로 차원이 증가할수록, 즉 feature가 많아질수록 예측 신뢰도가 떨어지고, 과적합(overfitting)이 발생하고, 개별 feature간의 상관관계가 높을 가능성이 있음

In [24]:
from sklearn.decomposition import PCA
# Initializing PCA and fitting
# Choose minimum number of PCA features that 85% variance is retained to avoid overfitting
pca = PCA(0.85)
X_sc_pca = pca.fit_transform(X_sc) # StandardScaler에서 학습용 데이터에 적용한 것처럼 fit과 transform 둘 다를 적용해줘야 하네~~??

In [25]:
# Transform train and test datasets
X_train_pca = pca.transform(X_train_sc)
X_test_pca = pca.transform(X_test_sc)

print('PCA차원 축소 이전 X_train:', X_train_sc.shape)
print('PCA차원 축소 이전 X_test:', X_test_sc.shape)
print('PCA차원 축소 이후 X_train:', X_train_pca.shape)
print('PCA차원 축소 이후 X_test:', X_test_pca.shape)

PCA차원 축소 이전 X_train: (2194, 445)
PCA차원 축소 이전 X_test: (732, 445)
PCA차원 축소 이후 X_train: (2194, 105)
PCA차원 축소 이후 X_test: (732, 105)

PCA차원 축소로 Feature가 446개에서 105개로 줄어 차원이 감소 됐음을 확인 할 수 있다.

## 2. Data Modeling

### 교차검증
- 보통은 train set 으로 모델을 훈련, test set으로 모델을 검증한다.고정된 test set을 통해 모델의 성능을 검증하고 수정하는 과정을 반복하면, 결국 내가 만든 모델은 test set 에만 잘 동작하는 모델이 된다.즉, test set에 과적합(overfitting)하게 되므로, 다른 실제 데이터를 가져와 예측을 수행하면 엉망인 결과가 나와버리게 된다.
- 교차 검증은 train set을 train set + validation set으로 분리한 뒤, validation set을 사용해 검증하는 방식이다.

In [26]:
#inport libraries
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import KFold  
from sklearn.model_selection import ShuffleSplit

from sklearn.model_selection import cross_val_score
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score, precision_score, average_precision_score
import warnings
warnings.filterwarnings(action='ignore')
# randomforest 에는 kFold 교차 검증 하는게 일반적 인듯..?

### K-fold : 
#### 모든 데이터를 Fold라고 불리는 그룹으로 나누고 이를 split 하여 데이터 자체에서 훈련 데이터, 테스트 데이터를 반복적으로 선정합니다.

### RepeatedStratifiedKFold : 
#### KFold를 n번 반복하는 반복자입니다. 각 반복마다 다른 분할을 생성하여 진행합니다.

### ShuffleSplit : 
#### 데이터를 먼저 섞은 후에 Fold를 분할하는 방식입니다. random_state를 통하여 난수를 제어할 수 있습니다. KFold의 대안으로 좀 더 세밀한 반복자를 형성하는 방식입니다.

In [27]:
X_train_pca.shape

(2194, 105)

In [28]:
y_train.shape

(2194,)

In [29]:
# Import Libraries
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score, precision_score,  classification_report, plot_confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
# randomforestclassifier 를 model 로 설정
model = DecisionTreeClassifier()
# 평가모델
rsk_fold = RepeatedStratifiedKFold(n_splits=50, n_repeats=3, random_state=0)
k_fold = KFold(n_splits=50, shuffle=True, random_state=0)        # shuffle = True -- default 값
ss = ShuffleSplit(n_splits=50, test_size=0.3, random_state=0)

n_scores_1 = cross_val_score(model, X_train_pca, y_train, scoring='accuracy', cv=rsk_fold, n_jobs=-1, error_score='raise')
n_scores_2 = cross_val_score(model, X_train_pca, y_train, scoring='accuracy', cv=k_fold, n_jobs=-1, error_score='raise')
n_scores_3 = cross_val_score(model, X_train_pca, y_train, scoring='accuracy', cv=ss, n_jobs=-1, error_score='raise')
# n_jobs=-1 로 하면 제한이 없어짐

print('Accuracy_1: %.3f (%.3f)' % (mean(n_scores_1), std(n_scores_1)))      # std 표준편차
print('Accuracy_2: %.3f (%.3f)' % (mean(n_scores_2), std(n_scores_2)))
print('Accuracy_3: %.3f (%.3f)' % (mean(n_scores_3), std(n_scores_3)))

Accuracy_1: 0.854 (0.052)
Accuracy_2: 0.857 (0.056)
Accuracy_3: 0.832 (0.017)

## 3. Data Evaluation
- TP(true positive): 1로 예측했을 때 정답도 1인 경우
- FP(false positive): 1로 예측했지만 정답은 0인 경우
- FN(false negative): 0으로 예측했지만 정답은 1인 경우
- TN(true negative): 0으로 예측했을 때 정답도 0인 경우
- recall(재현율)=TP/(TP+FN): 
  양성 positive 케이스들에서 진짜 true 양성 positive로 예측에 성공한 확률
- precision(정밀도)=TP/(TP+FP): 
  양성 positive라고 판단한 경우 중에 진짜 true 양성 positive인 확률
- F1_score=2∗(precision∗recall)/precision+recall

## Decision Tree

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score, precision_score,  classification_report, plot_confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
tree = DecisionTreeClassifier(random_state=0)
tree.fit(X_train_pca, y_train)
pred = tree.predict(X_test_pca)

In [31]:
acc = tree.score(X_test_pca, y_test)
print("Accuracy: {:.2f}%".format(acc * 100))

Accuracy: 84.56%

In [32]:
# Import Libraries
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score, precision_score

print('confusion_matrix', confusion_matrix(pred, y_test))
print('accuracy score', accuracy_score(pred, y_test))
print('f1_score', f1_score(y_test,pred))
print('recall_score', recall_score(pred, y_test))
print('precision_score',precision_score(y_test,pred))

confusion_matrix [[290  36]
 [ 77 329]]
accuracy score 0.8456284153005464
f1_score 0.8534370946822308
recall_score 0.8103448275862069
precision_score 0.8103448275862069

## gridcv - decisiontree

In [52]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, cross_val_score
from pylab import rcParams
trees = DecisionTreeClassifier(random_state=0, min_samples_split=6, min_samples_leaf=2)

In [53]:
params = { 'max_depth' : [20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60],
            }
grid_clf = GridSearchCV(trees, param_grid=params, scoring='accuracy', cv=10)
grid_clf.fit(X_train_pca, y_train)

print('최적의 하이퍼 파라미터:{0}, 최적의 평균 정확도:{1:.3f}'.format(grid_clf.best_params_, grid_clf.best_score_))

최적의 하이퍼 파라미터:{'max_depth': 32}, 최적의 평균 정확도:0.848

In [54]:
em = grid_clf.best_estimator_
pred = em.predict(X_test_pca)

print('confusion_matrix\n', confusion_matrix(pred, y_test))
print('accuracy score : ', accuracy_score(pred, y_test))
print('f1_score : ', f1_score(y_test,pred))
print('recall_score : ', recall_score(pred, y_test))
print('precision_score : ',precision_score(y_test,pred))

confusion_matrix
 [[300  48]
 [ 67 317]]
accuracy score :  0.842896174863388
f1_score :  0.8464619492656875
recall_score :  0.8255208333333334
precision_score :  0.8255208333333334

### 더 알아봐야함 밑에는 그래프 그리는거 대입하면 되고 하나더 밑에 scatter는 뭐 의미하는지 몰겄네

In [ ]:
Recall = np.array([84.4, 87.9, 81.3,9.4,0,0,0])
label = np.array(['Isolation Forest', 'Local Outlier Factor', 'Elliptic Envelop',
                  'Logistic','XGBoost','Random Forest','Lasso'])
indices = np.argsort(Recall)
color = plt.cm.rainbow(np.linspace(0, 1, 9))

plt.rcParams['figure.figsize'] = (18, 7)
plt.bar(range(len(indices)), Recall[indices], color = color)
plt.xticks(range(len(indices)), label[indices])
plt.title('Recall Accuracy - Normal Data', fontsize = 30)
plt.grid()
plt.tight_layout()
plt.show()

In [ ]:
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt

plt.title("3 Class values with 2 Features Sample Data Creation")

# 2차원 시각화를 위해 피처는 2개, 클래스는 3가지 유형의 분류 샘플 데이터 생성
X_features, y_labels = make_classification(n_features=2, n_redundant=0, n_informative=2,
                                                                  n_classes=1, n_clusters_per_class=1, random_state=0)

# 그래프 형태로 2개의 피쳐로 2차원 좌표 시각화, 각 클래스 값은 다른 색으로 표시
plt.scatter(X_features[:, 0], X_features[:, 1], marker='o', c=y_labels, s=25, edgecolor = 'k', cmap='rainbow')